source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-remote-theme", "~> 0.4"
gem "jekyll-include-cache", "~> 0.2"
gem "jekyll-feed", "~> 0.15"
gem "jekyll-sitemap", "~> 1.4"
gem "jekyll-paginate", "~> 1.1"
gem "jekyll-seo-tag", "~> 2.7"
gem "kramdown-parser-gfm", "~> 1.1"
gem "webrick", "~> 1.7"
gem "execjs", "~> 2.8"
gem "jekyll-sass-converter", ">= 2.0", "< 3.0"
gem "bigdecimal"